# Generated by Django 4.0.1 on 2022-01-15 14:02

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('body', models.CharField(max_length=500, verbose_name='Note')),
                ('updated', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
    ]
