# Generated by Django 4.0.1 on 2022-01-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.CharField(max_length=6000, verbose_name='Note'),
        ),
    ]
